name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "db_name_tests"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@drivent_db_tests:5432/db_name_tests"
          file_name: ".env.test"
      - name: Run integration tests
        run: docker-compose -f docker-compose-tests.yml run node_drivent npm run test:integration
      - name: Run unit tests
        run: docker-compose -f docker-compose-tests.yml run node_drivent npm run test:unit
